site_name: Xuewen Liu

nav:
  - Home: index.md
  - Project:
      - Rapid Meteor Detection: project/Meteordetection.md
      - My Tiny Observatory: project/Mytinyobservatory.md
  - CV : cv.md
  - Gallery: 
      - Deep Space Imaging: gellery/Deepspaceimaging.md
      - Planetary Imaging: gellery/Planetaryimaging.md



theme:
  logo: assets/images/icons8-pixel-heart-50.png
  favicon: assets/images/icons8-pixel-heart-50.png
  custom_dir: docs/overrides
  name: 'material'
  palette:
    scheme: default
    primary: black
    accent: deep orange


  features:
    - navigation.tabs
    - toc.integrate


plugins:
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
  - search:
      lang: 
        - en
        - de


extra:
  social:
    - icon: fontawesome/brands/weibo
      link: https://weibo.com/u/5544415122
      name: Weibo
    - icon: fontawesome/brands/github
      link: https://github.com/lewcherwyn
      name: Github
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/xuewen-liu-17462a2b5/
      name: LinkedIn

extra_css:
  - stylesheets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
extra_javascript:
  - javascripts/extra.js
  - javascripts/katex.js 
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js


markdown_extensions:
  - attr_list
  - md_in_html

copyright: Copyright &copy; 2023 Xuewen Liu
